# Service that routes to both versions
apiVersion: v1
kind: Service
metadata:
  name: color-app-service
  labels:
    app: color-app
spec:
  selector:
    app: color-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
# Deployment for v1.0.0 with 9 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app-v1-0-0
  labels:
    app: color-app
    version: v1.0.0
spec:
  replicas: 9
  selector:
    matchLabels:
      app: color-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: color-app
        version: v1.0.0
    spec:
      containers:
        - name: color-app
          image: denizgursoy/color-app:v1.0.0
          ports:
            - containerPort: 8080

---
# Deployment for v1.1.0 with 1 replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app-v1-1-0
  labels:
    app: color-app
    version: v1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-app
      version: v1.1.0
  template:
    metadata:
      labels:
        app: color-app
        version: v1.1.0
    spec:
      containers:
        - name: color-app
          image: denizgursoy/color-app:v1.1.0
          ports:
            - containerPort: 8080